apiVersion: v1
kind: Pod
metadata:
  labels:
    name: http-server
  name: http-server
  namespace: default
spec:
  containers:
    - name: http-server
      image: quay.io/crio/example-wasm-http:latest
      command: ["/http_server.wasm"]
      ports:
        - containerPort: 1234
          protocol: TCP
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      livenessProbe:
        tcpSocket:
          port: 1234
        initialDelaySeconds: 3
        periodSeconds: 30

