apiVersion: v1
kind: Pod
metadata:
  name: llama-pod
spec:
  containers:
  - name: llama-container
    image: quay.io/sohankunkerkar/llama-crun:v2
    volumeMounts:
    - name: wasm-volume
      mountPath: /app
    stdin: true   # Enable stdin for the container
    tty: true     # Enable tty for the container
  volumes:
  - name: wasm-volume
    hostPath:
      path: /home/skunkerk/wasm-test/
  restartPolicy: Never
