apiVersion: v1
kind: Pod
metadata:
  name: llama-pod
spec:
  containers:
  - name: llama-container
    image: quay.io/sohankunkerkar/llama-crun:v3
    volumeMounts:
    - name: wasm-volume
      mountPath: /app
    stdin: true
    tty: true
  volumes:
    - name: wasm-volume
      image:
        reference: quay.io/sohankunkerkar/wasm-ai-model:v1
        pullPolicy: IfNotPresent

